//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClientTestServer.QueryServer {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://microsoft.com/webservices/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassResponse))]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadOneMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadAllMemberExaminationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMembersOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOneMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOneMemberExaminationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOneMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOneMemberExaminationResponseOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOneMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOneMemberExaminationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::ClientTestServer.Properties.Settings.Default.ClientTestServer_QueryServer_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event ReadOneMemberCompletedEventHandler ReadOneMemberCompleted;
        
        /// <remarks/>
        public event ReadAllMemberExaminationsCompletedEventHandler ReadAllMemberExaminationsCompleted;
        
        /// <remarks/>
        public event ReadMembersCompletedEventHandler ReadMembersCompleted;
        
        /// <remarks/>
        public event UpdateOneMemberCompletedEventHandler UpdateOneMemberCompleted;
        
        /// <remarks/>
        public event UpdateOneMemberExaminationCompletedEventHandler UpdateOneMemberExaminationCompleted;
        
        /// <remarks/>
        public event CreateOneMemberCompletedEventHandler CreateOneMemberCompleted;
        
        /// <remarks/>
        public event CreateOneMemberExaminationResponseCompletedEventHandler CreateOneMemberExaminationResponseCompleted;
        
        /// <remarks/>
        public event DeleteOneMemberCompletedEventHandler DeleteOneMemberCompleted;
        
        /// <remarks/>
        public event DeleteOneMemberExaminationCompletedEventHandler DeleteOneMemberExaminationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/HelloWorld", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/ReadOneMember", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetMemberResponse ReadOneMember(GetMemberParameter pObjParamter) {
            object[] results = this.Invoke("ReadOneMember", new object[] {
                        pObjParamter});
            return ((GetMemberResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ReadOneMemberAsync(GetMemberParameter pObjParamter) {
            this.ReadOneMemberAsync(pObjParamter, null);
        }
        
        /// <remarks/>
        public void ReadOneMemberAsync(GetMemberParameter pObjParamter, object userState) {
            if ((this.ReadOneMemberOperationCompleted == null)) {
                this.ReadOneMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOneMemberOperationCompleted);
            }
            this.InvokeAsync("ReadOneMember", new object[] {
                        pObjParamter}, this.ReadOneMemberOperationCompleted, userState);
        }
        
        private void OnReadOneMemberOperationCompleted(object arg) {
            if ((this.ReadOneMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadOneMemberCompleted(this, new ReadOneMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/ReadAllMemberExaminations", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetMemberExaminationResponse ReadAllMemberExaminations(GetMemberExaminationParameter pObjParamter) {
            object[] results = this.Invoke("ReadAllMemberExaminations", new object[] {
                        pObjParamter});
            return ((GetMemberExaminationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAllMemberExaminationsAsync(GetMemberExaminationParameter pObjParamter) {
            this.ReadAllMemberExaminationsAsync(pObjParamter, null);
        }
        
        /// <remarks/>
        public void ReadAllMemberExaminationsAsync(GetMemberExaminationParameter pObjParamter, object userState) {
            if ((this.ReadAllMemberExaminationsOperationCompleted == null)) {
                this.ReadAllMemberExaminationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadAllMemberExaminationsOperationCompleted);
            }
            this.InvokeAsync("ReadAllMemberExaminations", new object[] {
                        pObjParamter}, this.ReadAllMemberExaminationsOperationCompleted, userState);
        }
        
        private void OnReadAllMemberExaminationsOperationCompleted(object arg) {
            if ((this.ReadAllMemberExaminationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadAllMemberExaminationsCompleted(this, new ReadAllMemberExaminationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/ReadMembers", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetMembersResponse ReadMembers(GetMemberParameter pObjParamter) {
            object[] results = this.Invoke("ReadMembers", new object[] {
                        pObjParamter});
            return ((GetMembersResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ReadMembersAsync(GetMemberParameter pObjParamter) {
            this.ReadMembersAsync(pObjParamter, null);
        }
        
        /// <remarks/>
        public void ReadMembersAsync(GetMemberParameter pObjParamter, object userState) {
            if ((this.ReadMembersOperationCompleted == null)) {
                this.ReadMembersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMembersOperationCompleted);
            }
            this.InvokeAsync("ReadMembers", new object[] {
                        pObjParamter}, this.ReadMembersOperationCompleted, userState);
        }
        
        private void OnReadMembersOperationCompleted(object arg) {
            if ((this.ReadMembersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMembersCompleted(this, new ReadMembersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/UpdateOneMember", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UpdateMemberResponse UpdateOneMember(UpdateMemberParameter pObjParamter) {
            object[] results = this.Invoke("UpdateOneMember", new object[] {
                        pObjParamter});
            return ((UpdateMemberResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOneMemberAsync(UpdateMemberParameter pObjParamter) {
            this.UpdateOneMemberAsync(pObjParamter, null);
        }
        
        /// <remarks/>
        public void UpdateOneMemberAsync(UpdateMemberParameter pObjParamter, object userState) {
            if ((this.UpdateOneMemberOperationCompleted == null)) {
                this.UpdateOneMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOneMemberOperationCompleted);
            }
            this.InvokeAsync("UpdateOneMember", new object[] {
                        pObjParamter}, this.UpdateOneMemberOperationCompleted, userState);
        }
        
        private void OnUpdateOneMemberOperationCompleted(object arg) {
            if ((this.UpdateOneMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOneMemberCompleted(this, new UpdateOneMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/UpdateOneMemberExamination", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UpdateMemberExaminationResponse UpdateOneMemberExamination(UpdateMemberExaminationParameter pObjParamter) {
            object[] results = this.Invoke("UpdateOneMemberExamination", new object[] {
                        pObjParamter});
            return ((UpdateMemberExaminationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOneMemberExaminationAsync(UpdateMemberExaminationParameter pObjParamter) {
            this.UpdateOneMemberExaminationAsync(pObjParamter, null);
        }
        
        /// <remarks/>
        public void UpdateOneMemberExaminationAsync(UpdateMemberExaminationParameter pObjParamter, object userState) {
            if ((this.UpdateOneMemberExaminationOperationCompleted == null)) {
                this.UpdateOneMemberExaminationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOneMemberExaminationOperationCompleted);
            }
            this.InvokeAsync("UpdateOneMemberExamination", new object[] {
                        pObjParamter}, this.UpdateOneMemberExaminationOperationCompleted, userState);
        }
        
        private void OnUpdateOneMemberExaminationOperationCompleted(object arg) {
            if ((this.UpdateOneMemberExaminationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOneMemberExaminationCompleted(this, new UpdateOneMemberExaminationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/CreateOneMember", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreateMemberResponse CreateOneMember(CreateMemberParameter pObjParamter) {
            object[] results = this.Invoke("CreateOneMember", new object[] {
                        pObjParamter});
            return ((CreateMemberResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOneMemberAsync(CreateMemberParameter pObjParamter) {
            this.CreateOneMemberAsync(pObjParamter, null);
        }
        
        /// <remarks/>
        public void CreateOneMemberAsync(CreateMemberParameter pObjParamter, object userState) {
            if ((this.CreateOneMemberOperationCompleted == null)) {
                this.CreateOneMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOneMemberOperationCompleted);
            }
            this.InvokeAsync("CreateOneMember", new object[] {
                        pObjParamter}, this.CreateOneMemberOperationCompleted, userState);
        }
        
        private void OnCreateOneMemberOperationCompleted(object arg) {
            if ((this.CreateOneMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOneMemberCompleted(this, new CreateOneMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/CreateOneMemberExaminationResponse", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreateMemberExaminationResponse CreateOneMemberExaminationResponse(CreateMemberExaminationParameter pObjParamter) {
            object[] results = this.Invoke("CreateOneMemberExaminationResponse", new object[] {
                        pObjParamter});
            return ((CreateMemberExaminationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOneMemberExaminationResponseAsync(CreateMemberExaminationParameter pObjParamter) {
            this.CreateOneMemberExaminationResponseAsync(pObjParamter, null);
        }
        
        /// <remarks/>
        public void CreateOneMemberExaminationResponseAsync(CreateMemberExaminationParameter pObjParamter, object userState) {
            if ((this.CreateOneMemberExaminationResponseOperationCompleted == null)) {
                this.CreateOneMemberExaminationResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOneMemberExaminationResponseOperationCompleted);
            }
            this.InvokeAsync("CreateOneMemberExaminationResponse", new object[] {
                        pObjParamter}, this.CreateOneMemberExaminationResponseOperationCompleted, userState);
        }
        
        private void OnCreateOneMemberExaminationResponseOperationCompleted(object arg) {
            if ((this.CreateOneMemberExaminationResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOneMemberExaminationResponseCompleted(this, new CreateOneMemberExaminationResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/DeleteOneMember", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeleteMemberResponse DeleteOneMember(DeleteMemberParameter pObjParamter) {
            object[] results = this.Invoke("DeleteOneMember", new object[] {
                        pObjParamter});
            return ((DeleteMemberResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteOneMemberAsync(DeleteMemberParameter pObjParamter) {
            this.DeleteOneMemberAsync(pObjParamter, null);
        }
        
        /// <remarks/>
        public void DeleteOneMemberAsync(DeleteMemberParameter pObjParamter, object userState) {
            if ((this.DeleteOneMemberOperationCompleted == null)) {
                this.DeleteOneMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOneMemberOperationCompleted);
            }
            this.InvokeAsync("DeleteOneMember", new object[] {
                        pObjParamter}, this.DeleteOneMemberOperationCompleted, userState);
        }
        
        private void OnDeleteOneMemberOperationCompleted(object arg) {
            if ((this.DeleteOneMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteOneMemberCompleted(this, new DeleteOneMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/DeleteOneMemberExamination", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeleteMemberExaminationResponse DeleteOneMemberExamination(DeleteMemberExaminationParameter pObjParamter) {
            object[] results = this.Invoke("DeleteOneMemberExamination", new object[] {
                        pObjParamter});
            return ((DeleteMemberExaminationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteOneMemberExaminationAsync(DeleteMemberExaminationParameter pObjParamter) {
            this.DeleteOneMemberExaminationAsync(pObjParamter, null);
        }
        
        /// <remarks/>
        public void DeleteOneMemberExaminationAsync(DeleteMemberExaminationParameter pObjParamter, object userState) {
            if ((this.DeleteOneMemberExaminationOperationCompleted == null)) {
                this.DeleteOneMemberExaminationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOneMemberExaminationOperationCompleted);
            }
            this.InvokeAsync("DeleteOneMemberExamination", new object[] {
                        pObjParamter}, this.DeleteOneMemberExaminationOperationCompleted, userState);
        }
        
        private void OnDeleteOneMemberExaminationOperationCompleted(object arg) {
            if ((this.DeleteOneMemberExaminationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteOneMemberExaminationCompleted(this, new DeleteOneMemberExaminationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class GetMemberParameter {
        
        private int memberIDField;
        
        /// <remarks/>
        public int memberID {
            get {
                return this.memberIDField;
            }
            set {
                this.memberIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class DeleteMemberExaminationParameter {
        
        private ClassExamination objMemberExaminationField;
        
        /// <remarks/>
        public ClassExamination objMemberExamination {
            get {
                return this.objMemberExaminationField;
            }
            set {
                this.objMemberExaminationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ClassExamination {
        
        private int memberIDField;
        
        private int examinationIDField;
        
        private System.DateTime dateTimeField;
        
        private bool resultField;
        
        private string commentsField;
        
        /// <remarks/>
        public int memberID {
            get {
                return this.memberIDField;
            }
            set {
                this.memberIDField = value;
            }
        }
        
        /// <remarks/>
        public int examinationID {
            get {
                return this.examinationIDField;
            }
            set {
                this.examinationIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class DeleteMemberParameter {
        
        private ClassMember objMemberField;
        
        /// <remarks/>
        public ClassMember objMember {
            get {
                return this.objMemberField;
            }
            set {
                this.objMemberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ClassMember {
        
        private int memberIDField;
        
        private string memberNameField;
        
        private string memberTel1Field;
        
        private string memberTel2Field;
        
        private string memberAddressField;
        
        private string memberEmailField;
        
        /// <remarks/>
        public int memberID {
            get {
                return this.memberIDField;
            }
            set {
                this.memberIDField = value;
            }
        }
        
        /// <remarks/>
        public string memberName {
            get {
                return this.memberNameField;
            }
            set {
                this.memberNameField = value;
            }
        }
        
        /// <remarks/>
        public string memberTel1 {
            get {
                return this.memberTel1Field;
            }
            set {
                this.memberTel1Field = value;
            }
        }
        
        /// <remarks/>
        public string memberTel2 {
            get {
                return this.memberTel2Field;
            }
            set {
                this.memberTel2Field = value;
            }
        }
        
        /// <remarks/>
        public string memberAddress {
            get {
                return this.memberAddressField;
            }
            set {
                this.memberAddressField = value;
            }
        }
        
        /// <remarks/>
        public string memberEmail {
            get {
                return this.memberEmailField;
            }
            set {
                this.memberEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class CreateMemberExaminationParameter {
        
        private ClassExamination objMemberExaminationField;
        
        /// <remarks/>
        public ClassExamination objMemberExamination {
            get {
                return this.objMemberExaminationField;
            }
            set {
                this.objMemberExaminationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class CreateMemberParameter {
        
        private ClassMember objMemberField;
        
        /// <remarks/>
        public ClassMember objMember {
            get {
                return this.objMemberField;
            }
            set {
                this.objMemberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class UpdateMemberExaminationParameter {
        
        private ClassExamination objMemberExaminationField;
        
        /// <remarks/>
        public ClassExamination objMemberExamination {
            get {
                return this.objMemberExaminationField;
            }
            set {
                this.objMemberExaminationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class UpdateMemberParameter {
        
        private ClassMember objMemberField;
        
        /// <remarks/>
        public ClassMember objMember {
            get {
                return this.objMemberField;
            }
            set {
                this.objMemberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class GetMemberExaminationParameter {
        
        private int memberIDField;
        
        /// <remarks/>
        public int memberID {
            get {
                return this.memberIDField;
            }
            set {
                this.memberIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteMemberExaminationResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteMemberResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateMemberExaminationResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateMemberResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateMemberExaminationResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateMemberResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetMembersResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetMemberExaminationResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetMemberResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ClassResponse {
        
        private string[] systemErrorsField;
        
        /// <remarks/>
        public string[] systemErrors {
            get {
                return this.systemErrorsField;
            }
            set {
                this.systemErrorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class DeleteMemberExaminationResponse : ClassResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class DeleteMemberResponse : ClassResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class CreateMemberExaminationResponse : ClassResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class CreateMemberResponse : ClassResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class UpdateMemberExaminationResponse : ClassResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class UpdateMemberResponse : ClassResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class GetMembersResponse : ClassResponse {
        
        private ClassMember[] listMembersField;
        
        /// <remarks/>
        public ClassMember[] listMembers {
            get {
                return this.listMembersField;
            }
            set {
                this.listMembersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class GetMemberExaminationResponse : ClassResponse {
        
        private ClassExamination[] listMemberExaminationsField;
        
        /// <remarks/>
        public ClassExamination[] listMemberExaminations {
            get {
                return this.listMemberExaminationsField;
            }
            set {
                this.listMemberExaminationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class GetMemberResponse : ClassResponse {
        
        private ClassMember memberObjField;
        
        /// <remarks/>
        public ClassMember memberObj {
            get {
                return this.memberObjField;
            }
            set {
                this.memberObjField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ReadOneMemberCompletedEventHandler(object sender, ReadOneMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadOneMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadOneMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetMemberResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetMemberResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ReadAllMemberExaminationsCompletedEventHandler(object sender, ReadAllMemberExaminationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadAllMemberExaminationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadAllMemberExaminationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetMemberExaminationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetMemberExaminationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ReadMembersCompletedEventHandler(object sender, ReadMembersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMembersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMembersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetMembersResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetMembersResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UpdateOneMemberCompletedEventHandler(object sender, UpdateOneMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOneMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOneMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateMemberResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateMemberResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UpdateOneMemberExaminationCompletedEventHandler(object sender, UpdateOneMemberExaminationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOneMemberExaminationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOneMemberExaminationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateMemberExaminationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateMemberExaminationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateOneMemberCompletedEventHandler(object sender, CreateOneMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOneMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOneMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateMemberResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateMemberResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateOneMemberExaminationResponseCompletedEventHandler(object sender, CreateOneMemberExaminationResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOneMemberExaminationResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOneMemberExaminationResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateMemberExaminationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateMemberExaminationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DeleteOneMemberCompletedEventHandler(object sender, DeleteOneMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteOneMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteOneMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteMemberResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteMemberResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DeleteOneMemberExaminationCompletedEventHandler(object sender, DeleteOneMemberExaminationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteOneMemberExaminationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteOneMemberExaminationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteMemberExaminationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteMemberExaminationResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591